version: '2'
services:
  mhacks_db:
    extends:
      file: docker-compose.yml
      service: mhacks_db
  mhacks_website:
    extends:
      file: docker-compose.yml
      service: mhacks_website
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/src/app
    command: sh -c "yarn install && nodemon app.js"
    environment:
      - DEBUG
      - APIWORK
      - MAILCHIMP_TOKEN
      - MANDRILL_TOKEN
      - HOST
      - DEPLOYMENT_SECRET
    links:
      - mhacks_db