version: '2'
services:
  mh_db:
    extends:
      file: docker-compose.yml
      service: mh_db
  mh_website:
    extends:
      file: docker-compose.yml
      service: mh_website
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/src/app
    command: sh -c "yarn install && nodemon app.js"
    environment:
      - DEBUG
      - APIWORK
      - MAILCHIMP_TOKEN
      - MANDRILL_TOKEN
      - HOST
      - DEPLOYMENT_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NEWRELIC_ENABLED
      - NEWRELIC_APP_NAME
      - NEWRELIC_LICENSE_KEY
    links:
      - mh_db
