// api endpoints
export default {
    SUBSCRIBE: '/v1/email/subscribe',
    REGISTER: '/v1/auth/register',
    RESET: '/v1/auth/password',
    VERIFY: '/v1/auth/verify',
    LOGIN: '/v1/auth/login',
    LOGOUT: '/v1/auth/logout',
    PROFILE: '/v1/user/profile',
    TICKET: '/v1/user/ticket',
    TICKET_PASSBOOK: '/v1/user/ticket/passbook',
    ALL_HACKER_APPLICATIONS: '/v1/application/all',
    APPLICATION: '/v1/application',
    CONFIRMATION: '/v1/application/confirm',
    READER: '/v1/reader',
    ANNOUNCEMENTS: '/v1/announcements',
    EVENTS: '/v1/event',
    CONFIGURATION: '/v1/configuration',
    FORM: '/v1/form/',
    SPONSOR: '/v1/sponsor',
    ALL_SPONSOR_PORTAL_APPLICATIONS: '/v1/application/all/sponsor',
    ALL_MENTOR_APPLICATIONS: '/v1/mentor/all',
    MENTOR_APPLICATION: '/v1/mentor/application',
    MENTOR_APPLICATION_FORM: '/v1/form/MentorApplication',
    ALL_SPEAKER_APPLICATIONS: '/v1/speaker/all',
    SPEAKER_APPLICATION: '/v1/speaker/application',
    SPEAKER_APPLICATION_FORM: '/v1/form/SpeakerApplication',
    ALL_APPLICATION_RESUMES: '/v1/artifact/resumes?application=true',
    TEAM_BUILDING: '/v1/teams/',
    TEAM_BUILDING_FORM: '/v1/form/Team',
    ADMIN_MODELS: '/v1/admin/model',

    MENTORSHIP_TICKETS: '/v1/mentorship',
    MENTORSHIP_TICKET_FORM: '/v1/form/MentorshipTicket',
    ACCEPT_MENTORSHIP_TICKET: '/v1/mentorship/accept',
    UNACCEPT_MENTORSHIP_TICKET: '/v1/mentorship/unaccept',
    COMPLETE_MENTORSHIP_TICKET: '/v1/mentorship/complete'
};
