#!/bin/bash

cd ~/mhacks-web/ && git pull

cd deploy/ && \
    /opt/bin/docker-compose -f production.yml pull --ignore-pull-failures && \
    /opt/bin/docker-compose -f production.yml build --pull mhacks_website mhacks_shortener && \
    /opt/bin/docker-compose -f production.yml up --no-deps -d mhacks_website mhacks_shortener
    
docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null

cd ~/mhacks-web/ && git --no-pager log --stat -n 2
